apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  storageClassName: ovirt-csi-sc
  accessModes:
  - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi