apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  storageClassName: ovirt-csi-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi